const Data = {
    HeroProducts: [
        {
            pId: "P1201",
            pTag: "LUMORA ATELIER",
            pName: "Premium Linen Co-ord Set",
            pPrice: "4,999",
            pDiscount: 20,
            pRating: "5",
            pRiview: 153,
            pMainImage: "ProductImages/Product1/product01_01.jpeg",
            pImage1: "ProductImages/Product1/product01_02.jpeg",
            pImage2: "ProductImages/Product1/product01_03.jpeg",
            pImage3: "ProductImages/Product1/product01_04.jpeg",
            pImage4: "ProductImages/Product1/product01_05.jpeg",
            pDesc: "Breathable Luxury linen with timeless elegance."
        },
        {
            pId: "P1202",
            pTag: "EVENING COLLECTION",
            pName: "Luxury Satin Maxi Dress",
            pPrice: "5,499",
            pDiscount: 5,
            pRating: "5",
            pRiview: 113,
            pMainImage: "ProductImages/Product2/product02_01.jpeg",
            pImage1: "ProductImages/Product2/product02_02.jpeg",
            pImage2: "ProductImages/Product2/product02_03.jpeg",
            pImage3: "ProductImages/Product2/product02_04.jpeg",
            pImage4: "ProductImages/Product2/product02_05.jpeg",
            pDesc: "Graceful satin drape designed for elegant evenings."
        },
        {
            pId: "P1203",
            pTag: "SIGNATURE LEATHER",
            pName: "Structured Leather Handbag",
            pPrice: "4,999",
            pDiscount: 33,
            pRating: "5",
            pRiview: 189,
            pMainImage: "ProductImages/Product3/product03_01.jpeg",
            pImage1: "ProductImages/Product3/product03_02.jpeg",
            pImage2: "ProductImages/Product3/product03_03.jpeg",
            pImage3: "ProductImages/Product3/product03_04.jpeg",
            pImage4: "ProductImages/Product3/product03_05.jpeg",
            pDesc: "Premium leather craftsmanship for everyday luxury."
        },
        {
            pId: "P1204",
            pTag: "WALK COLLECTION",
            pName: "Premium Leather Block Heals",
            pPrice: "3,999",
            pDiscount: 10,
            pRating: "5",
            pRiview: 100,
            pMainImage: "ProductImages/Product4/product04_01.jpeg",
            pImage1: "ProductImages/Product4/product04_02.jpeg",
            pImage2: "ProductImages/Product4/product04_03.jpeg",
            pImage3: "ProductImages/Product4/product04_04.jpeg",
            pImage4: "ProductImages/Product4/product04_05.jpeg",
            pDesc: "Elegant comfort crafted for all-day confidence."
        },
        {
            pId: "P1205",
            pTag: "POWER DRESSING",
            pName: "Premium Oversized Blazer",
            pPrice: "5,999",
            pDiscount: 22,
            pRating: "5",
            pRiview: 253,
            pMainImage: "ProductImages/Product5/product05_01.jpeg",
            pImage1: "ProductImages/Product5/product05_02.jpeg",
            pImage2: "ProductImages/Product5/product05_03.jpeg",
            pImage3: "ProductImages/Product5/product05_04.jpeg",
            pImage4: "ProductImages/Product5/product05_05.jpeg",
            pDesc: "Relaxed tailoring with timeless sophistication"
        },
        {
            pId: "P1206",
            pTag: "MODERN ESSENTIALS",
            pName: "Premium Silk Shirt",
            pPrice: "4,999",
            pDiscount: 20,
            pRating: "5",
            pRiview: 53,
            pMainImage: "ProductImages/Product6/product06_01.jpeg",
            pImage1: "ProductImages/Product6/product06_02.jpeg",
            pImage2: "ProductImages/Product6/product06_03.jpeg",
            pImage3: "ProductImages/Product6/product06_04.jpeg",
            pImage4: "ProductImages/Product6/product06_05.jpeg",
            pDesc: "Pure Silk Comfort with refined luxury styling."
        },
        {
            pId: "P1207",
            pTag: "POWER DRESSING",
            pName: "Cropped Leather jacket",
            pPrice: "8,999",
            pDiscount: 15,
            pRating: "5",
            pRiview: 139,
            pMainImage: "ProductImages/Product7/product07_01.jpeg",
            pImage1: "ProductImages/Product7/product07_02.jpeg",
            pImage2: "ProductImages/Product7/product07_03.jpeg",
            pImage3: "ProductImages/Product7/product07_04.jpeg",
            pImage4: "ProductImages/Product7/product07_05.jpeg",
            pDesc: "Genuine lambskin crafted for bold luxury."
        },
        {
            pId: "P1208",
            pTag: "LUXURY ACCESSORIES",
            pName: "Luxury Cat-Eye Sunglasses",
            pPrice: "3,499",
            pDiscount: 30,
            pRating: "5",
            pRiview: 183,
            pMainImage: "ProductImages/Product8/product08_01.jpeg",
            pImage1: "ProductImages/Product8/product08_02.jpeg",
            pImage2: "ProductImages/Product8/product08_03.jpeg",
            pImage3: "ProductImages/Product8/product08_04.jpeg",
            pImage4: "ProductImages/Product8/product08_05.jpeg",
            pDesc: "Elegant UV protection with timeless style"
        },
        {
            pId: "P1209",
            pTag: "SIGNATURE LEATHER",
            pName: "Premium Leather Purse",
            pPrice: "7,499",
            pDiscount: 15,
            pRating: "5",
            pRiview: 177,
            pMainImage: "ProductImages/Product9/product09_01.jpeg",
            pImage1: "ProductImages/Product9/product09_02.jpeg",
            pImage2: "ProductImages/Product9/product09_03.jpeg",
            pImage3: "ProductImages/Product9/product09_04.jpeg",
            pImage4: "ProductImages/Product9/product09_05.jpeg",
            pDesc: "Minimal luxury designed for effortless elegance."
        },
        {
            pId: "P1210",
            pTag: "FRAGRANCE COLLECTION",
            pName: "lumora No. 1 velvet Bloom",
            pPrice: "1,500",
            pDiscount: 50,
            pRating: "5",
            pRiview: 145,
            pMainImage: "ProductImages/Product10/product10_01.jpeg",
            pImage1: "ProductImages/Product10/product10_02.jpeg",
            pImage2: "ProductImages/Product10/product10_03.jpeg",
            pImage3: "ProductImages/Product10/product10_04.jpeg",
            pImage4: "ProductImages/Product10/product10_05.jpeg",
            pDesc: "A luxuious floral fragrance with warm amber notes"
        },
        {
            pId: "P1211",
            pTag: "FINE COLLECTION",
            pName: "Aurora Pearl Drop Earings",
            pPrice: "2,999",
            pDiscount: 10,
            pRating: "5",
            pRiview: 200,
            pMainImage: "ProductImages/Product11/product11_01.jpeg",
            pImage1: "ProductImages/Product11/product11_02.jpeg",
            pImage2: "ProductImages/Product11/product11_03.jpeg",
            pImage3: "ProductImages/Product11/product11_04.jpeg",
            pImage4: "ProductImages/Product11/product11_05.jpeg",
            pDesc: "Elegant pearls paired with brilliant craftsmanship."
        },
        {
            pId: "P1212",
            pTag: "TIME COLLECTION",
            pName: "Caleste Moon Women's Watch",
            pPrice: "880",
            pDiscount: 5,
            pRating: "5",
            pRiview: 223,
            pMainImage: "ProductImages/Product12/product12_01.jpeg",
            pImage1: "ProductImages/Product12/product12_02.jpeg",
            pImage2: "ProductImages/Product12/product12_03.jpeg",
            pImage3: "ProductImages/Product12/product12_04.jpeg",
            pImage4: "ProductImages/Product12/product12_05.jpeg",
            pDesc: "Timeless precision wrapped in modern elegance."
        } 
    ]
}
