const Data = {
    HeroProducts: [
        {
            pId: "P1201",
            pTag: "LUMORA ATELIER",
            pName: "Premium Linen Co-ord Set",
            pPrice: "4,999",
            pDiscount: 20,
            pRating: "5",
            pRiview: 153,
            pMainImage: "ProductImages/Product1/product01_01.jpeg",
            pImage1: "ProductImages/Product1/product01_02.jpeg",
            pImage2: "ProductImages/Product1/product01_03.jpeg",
            pImage3: "ProductImages/Product1/product01_04.jpeg",
            pImage4: "ProductImages/Product1/product01_05.jpeg",
            pDesc: "Breathable Luxury linen with timeless elegance."
        },
        {
            pId: "P1202",
            pTag: "EVENING COLLECTION",
            pName: "Luxury Satin Maxi Dress",
            pPrice: "5,499",
            pDiscount: 5,
            pRating: "5",
            pRiview: 113,
            pMainImage: "ProductImages/Product2/product02_01.jpeg",
            pImage1: "ProductImages/Product2/product02_02.jpeg",
            pImage2: "ProductImages/Product2/product02_03.jpeg",
            pImage3: "ProductImages/Product2/product02_04.jpeg",
            pImage4: "ProductImages/Product2/product02_05.jpeg",
            pDesc: "Graceful satin drape designed for elegant evenings."
        },
        {
            pId: "P1203",
            pTag: "SIGNATURE LEATHER",
            pName: "Structured Leather Handbag",
            pPrice: "4,999",
            pDiscount: 33,
            pRating: "5",
            pRiview: 189,
            pMainImage: "ProductImages/Product3/product03_01.jpeg",
            pImage1: "ProductImages/Product3/product03_02.jpeg",
            pImage2: "ProductImages/Product3/product03_03.jpeg",
            pImage3: "ProductImages/Product3/product03_04.jpeg",
            pImage4: "ProductImages/Product3/product03_05.jpeg",
            pDesc: "Premium leather craftsmanship for everyday luxury."
        },
        {
            pId: "P1204",
            pTag: "WALK COLLECTION",
            pName: "Premium Leather Block Heals",
            pPrice: "3,999",
            pDiscount: 10,
            pRating: "5",
            pRiview: 100,
            pMainImage: "ProductImages/Product4/product04_01.jpeg",
            pImage1: "ProductImages/Product4/product04_02.jpeg",
            pImage2: "ProductImages/Product4/product04_03.jpeg",
            pImage3: "ProductImages/Product4/product04_04.jpeg",
            pImage4: "ProductImages/Product4/product04_05.jpeg",
            pDesc: "Elegant comfort crafted for all-day confidence."
        },
        {
            pId: "P1205",
            pTag: "POWER DRESSING",
            pName: "Premium Oversized Blazer",
            pPrice: "5,999",
            pDiscount: 22,
            pRating: "5",
            pRiview: 253,
            pMainImage: "ProductImages/Product5/product05_01.jpeg",
            pImage1: "ProductImages/Product5/product05_02.jpeg",
            pImage2: "ProductImages/Product5/product05_03.jpeg",
            pImage3: "ProductImages/Product5/product05_04.jpeg",
            pImage4: "ProductImages/Product5/product05_05.jpeg",
            pDesc: "Relaxed tailoring with timeless sophistication"
        },
        {
            pId: "P1206",
            pTag: "MODERN ESSENTIALS",
            pName: "Premium Silk Shirt",
            pPrice: "4,999",
            pDiscount: 20,
            pRating: "5",
            pRiview: 53,
            pMainImage: "ProductImages/Product6/product06_01.jpeg",
            pImage1: "ProductImages/Product6/product06_02.jpeg",
            pImage2: "ProductImages/Product6/product06_03.jpeg",
            pImage3: "ProductImages/Product6/product06_04.jpeg",
            pImage4: "ProductImages/Product6/product06_05.jpeg",
            pDesc: "Pure Silk Comfort with refined luxury styling."
        },
        {
            pId: "P1207",
            pTag: "POWER DRESSING",
            pName: "Cropped Leather jacket",
            pPrice: "8,999",
            pDiscount: 15,
            pRating: "5",
            pRiview: 139,
            pMainImage: "ProductImages/Product7/product07_01.jpeg",
            pImage1: "ProductImages/Product7/product07_02.jpeg",
            pImage2: "ProductImages/Product7/product07_03.jpeg",
            pImage3: "ProductImages/Product7/product07_04.jpeg",
            pImage4: "ProductImages/Product7/product07_05.jpeg",
            pDesc: "Genuine lambskin crafted for bold luxury."
        },
        {
            pId: "P1208",
            pTag: "LUXURY ACCESSORIES",
            pName: "Luxury Cat-Eye Sunglasses",
            pPrice: "3,499",
            pDiscount: 30,
            pRating: "5",
            pRiview: 183,
            pMainImage: "ProductImages/Product8/product08_01.jpeg",
            pImage1: "ProductImages/Product8/product08_02.jpeg",
            pImage2: "ProductImages/Product8/product08_03.jpeg",
            pImage3: "ProductImages/Product8/product08_04.jpeg",
            pImage4: "ProductImages/Product8/product08_05.jpeg",
            pDesc: "Elegant UV protection with timeless style"
        },
        {
            pId: "P1209",
            pTag: "SIGNATURE LEATHER",
            pName: "Premium Leather Purse",
            pPrice: "7,499",
            pDiscount: 15,
            pRating: "5",
            pRiview: 177,
            pMainImage: "ProductImages/Product9/product09_01.jpeg",
            pImage1: "ProductImages/Product9/product09_02.jpeg",
            pImage2: "ProductImages/Product9/product09_03.jpeg",
            pImage3: "ProductImages/Product9/product09_04.jpeg",
            pImage4: "ProductImages/Product9/product09_05.jpeg",
            pDesc: "Minimal luxury designed for effortless elegance."
        },
        {
            pId: "P1210",
            pTag: "FRAGRANCE COLLECTION",
            pName: "lumora No. 1 velvet Bloom",
            pPrice: "1,500",
            pDiscount: 50,
            pRating: "5",
            pRiview: 145,
            pMainImage: "ProductImages/Product10/product10_01.jpeg",
            pImage1: "ProductImages/Product10/product10_02.jpeg",
            pImage2: "ProductImages/Product10/product10_03.jpeg",
            pImage3: "ProductImages/Product10/product10_04.jpeg",
            pImage4: "ProductImages/Product10/product10_05.jpeg",
            pDesc: "A luxuious floral fragrance with warm amber notes"
        },
        {
            pId: "P1211",
            pTag: "FINE COLLECTION",
            pName: "Aurora Pearl Drop Earings",
            pPrice: "2,999",
            pDiscount: 10,
            pRating: "5",
            pRiview: 200,
            pMainImage: "ProductImages/Product11/product11_01.jpeg",
            pImage1: "ProductImages/Product11/product11_02.jpeg",
            pImage2: "ProductImages/Product11/product11_03.jpeg",
            pImage3: "ProductImages/Product11/product11_04.jpeg",
            pImage4: "ProductImages/Product11/product11_05.jpeg",
            pDesc: "Elegant pearls paired with brilliant craftsmanship."
        },
        {
            pId: "P1212",
            pTag: "TIME COLLECTION",
            pName: "Caleste Moon Women's Watch",
            pPrice: "880",
            pDiscount: 5,
            pRating: "5",
            pRiview: 223,
            pMainImage: "ProductImages/Product12/product12_01.jpeg",
            pImage1: "ProductImages/Product12/product12_02.jpeg",
            pImage2: "ProductImages/Product12/product12_03.jpeg",
            pImage3: "ProductImages/Product12/product12_04.jpeg",
            pImage4: "ProductImages/Product12/product12_05.jpeg",
            pDesc: "Timeless precision wrapped in modern elegance."
        },
        {
            pId: "P1213",
            pTag: "FINE COLLECTION",
            pName: "Luna Tennis Bracelet",
            pPrice: "3,999",
            pDiscount: 25,
            pRating: "5",
            pRiview: 276,
            pMainImage: "ProductImages/Product13/product13_01.jpeg",
            pImage1: "ProductImages/Product13/product13_02.jpeg",
            pImage2: "ProductImages/Product13/product13_03.jpeg",
            pImage3: "ProductImages/Product13/product13_04.jpeg",
            pImage4: "ProductImages/Product13/product13_05.jpeg",
            pDesc: "Brilliant diamonds crafted for timeless elegance."
        },
        {
            pId: "P1214",
            pTag: "WALK COLLECTION",
            pName: "Luxury White Leather Sneakers",
            pPrice: "6,499",
            pDiscount: 15,
            pRating: "5",
            pRiview: 194,
            pMainImage: "ProductImages/Product14/product14_01.jpeg",
            pImage1: "ProductImages/Product14/product14_02.jpeg",
            pImage2: "ProductImages/Product14/product14_03.jpeg",
            pImage3: "ProductImages/Product14/product14_04.jpeg",
            pImage4: "ProductImages/Product14/product14_05.jpeg",
            pDesc: "Italian leather comfort with effortless luxury."
        },
        {
            pId: "P1215",
            pTag: "ATELIER COLLECTION",
            pName: "Premium Cashmere Scarf",
            pPrice: "2,999",
            pDiscount: 20,
            pRating: "5",
            pRiview: 148,
            pMainImage: "ProductImages/Product15/product15_01.jpeg",
            pImage1: "ProductImages/Product15/product15_02.jpeg",
            pImage2: "ProductImages/Product15/product15_03.jpeg",
            pImage3: "ProductImages/Product15/product15_04.jpeg",
            pImage4: "ProductImages/Product15/product15_05.jpeg",
            pDesc: "Ultra-soft cashmere crafted for everyday sophistication."
        },
        {
            pId: "P1216",
            pTag: "SIGNATURE LEATHER",
            pName: "Luxury Leather Tote Bag",
            pPrice: "8,999",
            pDiscount: 18,
            pRating: "5",
            pRiview: 231,
            pMainImage: "ProductImages/Product16/product16_01.jpeg",
            pImage1: "ProductImages/Product16/product16_02.jpeg",
            pImage2: "ProductImages/Product16/product16_03.jpeg",
            pImage3: "ProductImages/Product16/product16_04.jpeg",
            pImage4: "ProductImages/Product16/product16_05.jpeg",
            pDesc: "Elegant functionality crafted from premium Italian leather."
        },
        {
            pId: "P1217",
            pTag: "MODERN ESSENTIALS",
            pName: "Wide-Leg Tailored Trousers",
            pPrice: "4,499",
            pDiscount: 12,
            pRating: "5",
            pRiview: 167,
            pMainImage: "ProductImages/Product17/product17_01.jpeg",
            pImage1: "ProductImages/Product17/product17_02.jpeg",
            pImage2: "ProductImages/Product17/product17_03.jpeg",
            pImage3: "ProductImages/Product17/product17_04.jpeg",
            pImage4: "ProductImages/Product17/product17_05.jpeg",
            pDesc: "Modern tailoring with refined comfort and elegance."
        },
        {
            pId: "P1218",
            pTag: "EVENING COLLECTION",
            pName: "Luxury Silk Wrap Dress",
            pPrice: "7,999",
            pDiscount: 22,
            pRating: "5",
            pRiview: 203,
            pMainImage: "ProductImages/Product18/product18_01.jpeg",
            pImage1: "ProductImages/Product18/product18_02.jpeg",
            pImage2: "ProductImages/Product18/product18_03.jpeg",
            pImage3: "ProductImages/Product18/product18_04.jpeg",
            pImage4: "ProductImages/Product18/product18_05.jpeg",
            pDesc: "Flowing silk elegance designed for unforgettable evenings."
        },
        {
            pId: "P1219",
            pTag: "SIGNATURE LEATHER",
            pName: "Luxury Leather Crossbody Bag",
            pPrice: "7,499",
            pDiscount: 20,
            pRating: "5",
            pRiview: 188,
            pMainImage: "ProductImages/Product19/product19_01.jpeg",
            pImage1: "ProductImages/Product19/product19_02.jpeg",
            pImage2: "ProductImages/Product19/product19_03.jpeg",
            pImage3: "ProductImages/Product19/product19_04.jpeg",
            pImage4: "ProductImages/Product19/product19_05.jpeg",
            pDesc: "Compact luxury crafted for effortless everyday style."
        },
        {
            pId: "P1220",
            pTag: "HOME COLLECTION",
            pName: "Midnight Oud Soy Candle",
            pPrice: "2,499",
            pDiscount: 15,
            pRating: "5",
            pRiview: 118,
            pMainImage: "ProductImages/Product20/product20_01.jpeg",
            pImage1: "ProductImages/Product20/product20_02.jpeg",
            pImage2: "ProductImages/Product20/product20_03.jpeg",
            pImage3: "ProductImages/Product20/product20_04.jpeg",
            pImage4: "ProductImages/Product20/product20_05.jpeg",
            pDesc: "Warm oud and vanilla fragrance for luxurious living."
        },
        {
            pId: "P1221",
            pTag: "COUTURE COLLECTION",
            pName: "Royal Ivory Bridal Lehenga",
            pPrice: "24,999",
            pDiscount: 10,
            pRating: "5",
            pRiview: 142,
            pMainImage: "ProductImages/Product21/product21_01.jpeg",
            pImage1: "ProductImages/Product21/product21_02.jpeg",
            pImage2: "ProductImages/Product21/product21_03.jpeg",
            pImage3: "ProductImages/Product21/product21_04.jpeg",
            pImage4: "ProductImages/Product21/product21_05.jpeg",
            pDesc: "Handcrafted couture designed for timeless celebrations."
        },
        {
            pId: "P1222",
            pTag: "TIME COLLECTION",
            pName: "Celeste Étoile Moonphase Watch",
            pPrice: "8,999",
            pDiscount: 12,
            pRating: "5",
            pRiview: 223,
            pMainImage: "ProductImages/Product22/product22_01.jpeg",
            pImage1: "ProductImages/Product22/product22_02.jpeg",
            pImage2: "ProductImages/Product22/product22_03.jpeg",
            pImage3: "ProductImages/Product22/product22_04.jpeg",
            pImage4: "ProductImages/Product22/product22_05.jpeg",
            pDesc: "Swiss-inspired precision wrapped in timeless elegance."
        }
    ]
}
