const Data = {
    HeroProducts: [
        {
            pId: "P1201",
            pCategory: "Clothing",
            pTag: "LUMORA ATELIER",
            pName: "Premium Linen Co-ord Set",
            pPrice: "4,995",
            pDiscount: null,
            pRating: "5",
            pRiview: 153,
            pBadge: null,
            pColorName: "Sand Beige",
            pColorHex: "#cdb994",
            pFabric: "Pure Linen",
            pOccasion: "Daywear, Casual Outings",
            pKeywords: ["linen", "co-ord set", "co-ord", "beige", "casual", "clothing", "atelier", "summer wear", "breathable"],
            pDim1Label: "Top Length",
            pDim1Value: "24 IN",
            pDim2Label: "Bottom Length",
            pDim2Value: "40 IN",
            pHighlights: [
                { icon: "spool", text: "100% Pure Linen Fabric" },
                { icon: "hanger", text: "Relaxed Co-ord Fit" },
                { icon: "leaf", text: "Breathable & Lightweight" },
                { icon: "hand", text: "Tailored for All-Day Comfort" },
                { icon: "shield", text: "Colorfast, Durable Weave" }
            ],
            pCareInstructions: [
                "Machine wash cold with similar colors; tumble dry on low heat.",
                "Iron on medium heat while slightly damp for a crisp finish."
            ],
            pMainImage: "ProductImages/Product1/product01_01.jpeg",
            pImage1: "ProductImages/Product1/product01_02.jpeg",
            pImage2: "ProductImages/Product1/product01_03.jpeg",
            pImage3: "ProductImages/Product1/product01_04.jpeg",
            pImage4: "ProductImages/Product1/product01_05.jpeg",
            pDesc: "Breathable Luxury linen with timeless elegance."
        },
        {
            pId: "P1202",
            pCategory: "Dresses",
            pTag: "EVENING COLLECTION",
            pName: "Luxury Satin Maxi Dress",
            pPrice: "5,499",
            pDiscount: 5,
            pRating: "5",
            pRiview: 113,
            pBadge: null,
            pColorName: "Champagne Gold",
            pColorHex: "#c9a86a",
            pFabric: "Premium Satin",
            pOccasion: "Evening, Party Wear",
            pKeywords: ["satin", "maxi dress", "evening wear", "party dress", "champagne", "gown", "dresses"],
            pDim1Label: "Dress Length",
            pDim1Value: "58 IN",
            pDim2Label: "Fit",
            pDim2Value: "Bodycon",
            pHighlights: [
                { icon: "spool", text: "Luxurious Satin Weave" },
                { icon: "wave", text: "Fluid Draping Silhouette" },
                { icon: "gem", text: "Subtle Sheen Finish" },
                { icon: "hanger", text: "Fully Lined for Comfort" },
                { icon: "hand", text: "Finished with French Seams" }
            ],
            pCareInstructions: [
                "Dry clean recommended to preserve the satin sheen.",
                "Store on a padded hanger away from direct sunlight."
            ],
            pMainImage: "ProductImages/Product2/product02_01.jpeg",
            pImage1: "ProductImages/Product2/product02_02.jpeg",
            pImage2: "ProductImages/Product2/product02_03.jpeg",
            pImage3: "ProductImages/Product2/product02_04.jpeg",
            pImage4: "ProductImages/Product2/product02_05.jpeg",
            pDesc: "Graceful satin drape designed for elegant evenings."
        },
        {
            pId: "P1203",
            pCategory: "Bags",
            pTag: "SIGNATURE LEATHER",
            pName: "Structured Leather Handbag",
            pPrice: "4,999",
            pDiscount: 33,
            pRating: "5",
            pRiview: 189,
            pBadge: "Hot Deal",
            pColorName: "Espresso Brown",
            pColorHex: "#4a2f22",
            pFabric: "Genuine Leather",
            pOccasion: "Everyday, Office",
            pKeywords: ["leather", "handbag", "bag", "brown", "office bag", "structured bag", "accessories"],
            pDim1Label: "Height",
            pDim1Value: "10 IN",
            pDim2Label: "Width",
            pDim2Value: "13 IN",
            pHighlights: [
                { icon: "spool", text: "Genuine Full-Grain Leather" },
                { icon: "shield", text: "Reinforced Structured Base" },
                { icon: "hanger", text: "Adjustable Shoulder Strap" },
                { icon: "gem", text: "Gold-Tone Hardware" },
                { icon: "hand", text: "Handstitched Detailing" }
            ],
            pCareInstructions: [
                "Wipe clean with a soft, dry cloth; avoid water contact.",
                "Store with the dust bag provided when not in use."
            ],
            pMainImage: "ProductImages/Product3/product03_01.jpeg",
            pImage1: "ProductImages/Product3/product03_02.jpeg",
            pImage2: "ProductImages/Product3/product03_03.jpeg",
            pImage3: "ProductImages/Product3/product03_04.jpeg",
            pImage4: "ProductImages/Product3/product03_05.jpeg",
            pDesc: "Premium leather craftsmanship for everyday luxury."
        },
        {
            pId: "P1204",
            pCategory: "Footwear",
            pTag: "WALK COLLECTION",
            pName: "Premium Leather Block Heals",
            pPrice: "3,999",
            pDiscount: 10,
            pRating: "5",
            pRiview: 100,
            pBadge: null,
            pColorName: "Nude Beige",
            pColorHex: "#d9b99a",
            pFabric: "Genuine Leather",
            pOccasion: "Daywear, Office, Evening",
            pKeywords: ["heels", "block heels", "leather shoes", "footwear", "nude", "office wear"],
            pDim1Label: "Heel Height",
            pDim1Value: "3 IN",
            pDim2Label: "Sole",
            pDim2Value: "Cushioned",
            pHighlights: [
                { icon: "spool", text: "Genuine Leather Upper" },
                { icon: "shield", text: "Non-Slip Rubber Sole" },
                { icon: "hand", text: "Cushioned Footbed for Comfort" },
                { icon: "hanger", text: "Adjustable Ankle Strap" },
                { icon: "award", text: "Handcrafted Block Heel" }
            ],
            pCareInstructions: [
                "Wipe with a dry cloth; avoid prolonged exposure to moisture.",
                "Use a shoe tree to help retain shape when storing."
            ],
            pMainImage: "ProductImages/Product4/product04_01.jpeg",
            pImage1: "ProductImages/Product4/product04_02.jpeg",
            pImage2: "ProductImages/Product4/product04_03.jpeg",
            pImage3: "ProductImages/Product4/product04_04.jpeg",
            pImage4: "ProductImages/Product4/product04_05.jpeg",
            pDesc: "Elegant comfort crafted for all-day confidence."
        },
        {
            pId: "P1205",
            pCategory: "Clothing",
            pTag: "POWER DRESSING",
            pName: "Premium Oversized Blazer",
            pPrice: "5,999",
            pDiscount: 22,
            pRating: "5",
            pRiview: 253,
            pBadge: "Trending",
            pColorName: "Charcoal Grey",
            pColorHex: "#3d3d3d",
            pFabric: "Wool Blend",
            pOccasion: "Office, Power Dressing",
            pKeywords: ["blazer", "oversized blazer", "power dressing", "grey", "office wear", "coat"],
            pDim1Label: "Length",
            pDim1Value: "30 IN",
            pDim2Label: "Fit",
            pDim2Value: "Oversized",
            pHighlights: [
                { icon: "spool", text: "Premium Wool-Blend Fabric" },
                { icon: "hanger", text: "Relaxed Oversized Fit" },
                { icon: "shield", text: "Structured Padded Shoulders" },
                { icon: "hand", text: "Fully Lined Interior" },
                { icon: "gem", text: "Statement Button Detailing" }
            ],
            pCareInstructions: [
                "Dry clean only to maintain the tailored structure.",
                "Steam gently to remove creases; avoid direct ironing."
            ],
            pMainImage: "ProductImages/Product5/product05_01.jpeg",
            pImage1: "ProductImages/Product5/product05_02.jpeg",
            pImage2: "ProductImages/Product5/product05_03.jpeg",
            pImage3: "ProductImages/Product5/product05_04.jpeg",
            pImage4: "ProductImages/Product5/product05_05.jpeg",
            pDesc: "Relaxed tailoring with timeless sophistication"
        },
        {
            pId: "P1206",
            pCategory: "Clothing",
            pTag: "MODERN ESSENTIALS",
            pName: "Premium Silk Shirt",
            pPrice: "4,999",
            pDiscount: 20,
            pRating: "5",
            pRiview: 53,
            pBadge: null,
            pColorName: "Ivory White",
            pColorHex: "#f0ead9",
            pFabric: "Pure Silk",
            pOccasion: "Office, Smart Casual",
            pKeywords: ["silk shirt", "shirt", "ivory", "office wear", "smart casual", "modern essentials"],
            pDim1Label: "Length",
            pDim1Value: "27 IN",
            pDim2Label: "Sleeve",
            pDim2Value: "Full Sleeve",
            pHighlights: [
                { icon: "spool", text: "100% Pure Mulberry Silk" },
                { icon: "wave", text: "Smooth Lustrous Finish" },
                { icon: "hanger", text: "Relaxed Tailored Fit" },
                { icon: "hand", text: "Mother-of-Pearl Buttons" },
                { icon: "leaf", text: "Breathable All-Day Wear" }
            ],
            pCareInstructions: [
                "Dry clean only; avoid direct contact with perfume.",
                "Store on a padded hanger to prevent creasing."
            ],
            pMainImage: "ProductImages/Product6/product06_01.jpeg",
            pImage1: "ProductImages/Product6/product06_02.jpeg",
            pImage2: "ProductImages/Product6/product06_03.jpeg",
            pImage3: "ProductImages/Product6/product06_04.jpeg",
            pImage4: "ProductImages/Product6/product06_05.jpeg",
            pDesc: "Pure Silk Comfort with refined luxury styling."
        },
        {
            pId: "P1207",
            pCategory: "Clothing",
            pTag: "POWER DRESSING",
            pName: "Cropped Leather jacket",
            pPrice: "8,999",
            pDiscount: 15,
            pRating: "5",
            pRiview: 139,
            pBadge: null,
            pColorName: "Jet Black",
            pColorHex: "#1a1a1a",
            pFabric: "Genuine Lambskin Leather",
            pOccasion: "Evening, Edgy Casual",
            pKeywords: ["leather jacket", "cropped jacket", "black jacket", "lambskin", "outerwear"],
            pDim1Label: "Length",
            pDim1Value: "20 IN",
            pDim2Label: "Fit",
            pDim2Value: "Cropped",
            pHighlights: [
                { icon: "spool", text: "Genuine Lambskin Leather" },
                { icon: "shield", text: "Soft Yet Durable Finish" },
                { icon: "hanger", text: "Fitted Cropped Silhouette" },
                { icon: "gem", text: "Silver-Tone Zipper Hardware" },
                { icon: "hand", text: "Quilted Satin Lining" }
            ],
            pCareInstructions: [
                "Wipe clean with a leather-specific cloth.",
                "Avoid direct sunlight and moisture for prolonged periods."
            ],
            pMainImage: "ProductImages/Product7/product07_01.jpeg",
            pImage1: "ProductImages/Product7/product07_02.jpeg",
            pImage2: "ProductImages/Product7/product07_03.jpeg",
            pImage3: "ProductImages/Product7/product07_04.jpeg",
            pImage4: "ProductImages/Product7/product07_05.jpeg",
            pDesc: "Genuine lambskin crafted for bold luxury."
        },
        {
            pId: "P1208",
            pCategory: "Accessories",
            pTag: "LUXURY ACCESSORIES",
            pName: "Luxury Cat-Eye Sunglasses",
            pPrice: "3,499",
            pDiscount: 30,
            pRating: "5",
            pRiview: 183,
            pBadge: null,
            pColorName: "Tortoise Brown",
            pColorHex: "#6b4a2f",
            pFabric: "Acetate Frame",
            pOccasion: "Everyday, Vacation",
            pKeywords: ["sunglasses", "cat-eye", "eyewear", "tortoise", "accessories", "uv protection"],
            pDim1Label: "UV Protection",
            pDim1Value: "UV400",
            pDim2Label: "Lens",
            pDim2Value: "Polarized",
            pHighlights: [
                { icon: "shield", text: "100% UV400 Protection" },
                { icon: "gem", text: "Polarized Anti-Glare Lenses" },
                { icon: "hanger", text: "Lightweight Acetate Frame" },
                { icon: "award", text: "Scratch-Resistant Coating" },
                { icon: "gift", text: "Comes with Protective Case" }
            ],
            pCareInstructions: [
                "Clean lenses with a microfiber cloth only.",
                "Store in the case provided to avoid scratches."
            ],
            pMainImage: "ProductImages/Product8/product08_01.jpeg",
            pImage1: "ProductImages/Product8/product08_02.jpeg",
            pImage2: "ProductImages/Product8/product08_03.jpeg",
            pImage3: "ProductImages/Product8/product08_04.jpeg",
            pImage4: "ProductImages/Product8/product08_05.jpeg",
            pDesc: "Elegant UV protection with timeless style"
        },
        {
            pId: "P1209",
            pCategory: "Bags",
            pTag: "SIGNATURE LEATHER",
            pName: "Premium Leather Purse",
            pPrice: "7,499",
            pDiscount: 15,
            pRating: "5",
            pRiview: 177,
            pBadge: null,
            pColorName: "Tan Brown",
            pColorHex: "#a97a4a",
            pFabric: "Genuine Leather",
            pOccasion: "Everyday, Travel",
            pKeywords: ["purse", "wallet", "leather purse", "tan", "everyday bag", "accessories"],
            pDim1Label: "Length",
            pDim1Value: "7.5 IN",
            pDim2Label: "Card Slots",
            pDim2Value: "8",
            pHighlights: [
                { icon: "spool", text: "Genuine Leather Construction" },
                { icon: "shield", text: "RFID-Blocking Lining" },
                { icon: "hanger", text: "Multiple Card & Cash Slots" },
                { icon: "gem", text: "Gold-Tone Zip Closure" },
                { icon: "hand", text: "Hand-Finished Edges" }
            ],
            pCareInstructions: [
                "Wipe with a soft, dry cloth to maintain shine.",
                "Avoid overstuffing to preserve the shape."
            ],
            pMainImage: "ProductImages/Product9/product09_01.jpeg",
            pImage1: "ProductImages/Product9/product09_02.jpeg",
            pImage2: "ProductImages/Product9/product09_03.jpeg",
            pImage3: "ProductImages/Product9/product09_04.jpeg",
            pImage4: "ProductImages/Product9/product09_05.jpeg",
            pDesc: "Minimal luxury designed for effortless elegance."
        },
        {
            pId: "P1210",
            pCategory: "Fragrance",
            pTag: "FRAGRANCE COLLECTION",
            pName: "lumora No. 1 velvet Bloom",
            pPrice: "1,500",
            pDiscount: 50,
            pRating: "5",
            pRiview: 145,
            pBadge: "Hot Deal",
            pColorName: "Deep Amber",
            pColorHex: "#8a4a1e",
            pFabric: "Eau de Parfum",
            pOccasion: "Day & Night Wear",
            pKeywords: ["perfume", "fragrance", "eau de parfum", "floral", "amber", "gift"],
            pDim1Label: "Volume",
            pDim1Value: "50 ML",
            pDim2Label: "Longevity",
            pDim2Value: "8+ Hours",
            pHighlights: [
                { icon: "gem", text: "Long-Lasting Amber Base Notes" },
                { icon: "leaf", text: "Blended with Natural Floral Extracts" },
                { icon: "gift", text: "Elegant Gift-Ready Bottle" },
                { icon: "shield", text: "Alcohol-Based, Skin-Safe Formula" },
                { icon: "award", text: "Perfumer-Crafted Blend" }
            ],
            pCareInstructions: [
                "Store in a cool, dry place away from direct sunlight.",
                "Best used within 12 months of opening for optimal scent."
            ],
            pMainImage: "ProductImages/Product10/product10_01.jpeg",
            pImage1: "ProductImages/Product10/product10_02.jpeg",
            pImage2: "ProductImages/Product10/product10_03.jpeg",
            pImage3: "ProductImages/Product10/product10_04.jpeg",
            pImage4: "ProductImages/Product10/product10_05.jpeg",
            pDesc: "A luxuious floral fragrance with warm amber notes"
        },
        {
            pId: "P1211",
            pCategory: "Jewellery",
            pTag: "FINE COLLECTION",
            pName: "Aurora Pearl Drop Earings",
            pPrice: "2,999",
            pDiscount: 10,
            pRating: "5",
            pRiview: 200,
            pBadge: null,
            pColorName: "Pearl White & Gold",
            pColorHex: "#e8dcb8",
            pFabric: "Gold-Plated Brass",
            pOccasion: "Wedding, Festive",
            pKeywords: ["earrings", "pearl earrings", "drop earrings", "jewellery", "gold", "fine collection"],
            pDim1Label: "Drop Length",
            pDim1Value: "2 IN",
            pDim2Label: "Closure",
            pDim2Value: "Push Back",
            pHighlights: [
                { icon: "gem", text: "Freshwater Pearl Accents" },
                { icon: "shield", text: "Tarnish-Resistant Gold Plating" },
                { icon: "hand", text: "Handset Craftsmanship" },
                { icon: "award", text: "Hypoallergenic Posts" },
                { icon: "gift", text: "Comes in a Signature Gift Box" }
            ],
            pCareInstructions: [
                "Avoid contact with water, perfume and lotions.",
                "Store separately in the pouch provided to prevent scratches."
            ],
            pMainImage: "ProductImages/Product11/product11_01.jpeg",
            pImage1: "ProductImages/Product11/product11_02.jpeg",
            pImage2: "ProductImages/Product11/product11_03.jpeg",
            pImage3: "ProductImages/Product11/product11_04.jpeg",
            pImage4: "ProductImages/Product11/product11_05.jpeg",
            pDesc: "Elegant pearls paired with brilliant craftsmanship."
        },
        {
            pId: "P1212",
            pCategory: "Watches",
            pTag: "TIME COLLECTION",
            pName: "Caleste Moon Women's Watch",
            pPrice: "880",
            pDiscount: 5,
            pRating: "5",
            pRiview: 223,
            pBadge: null,
            pColorName: "Rose Gold",
            pColorHex: "#c48a6a",
            pFabric: "Stainless Steel Case",
            pOccasion: "Everyday, Gifting",
            pKeywords: ["watch", "women's watch", "rose gold watch", "time collection", "wristwatch"],
            pDim1Label: "Dial Size",
            pDim1Value: "32 MM",
            pDim2Label: "Water Resistance",
            pDim2Value: "3 ATM",
            pHighlights: [
                { icon: "shield", text: "Scratch-Resistant Mineral Glass" },
                { icon: "gem", text: "Rose Gold-Tone Finish" },
                { icon: "award", text: "Precision Quartz Movement" },
                { icon: "lock", text: "3 ATM Water Resistance" },
                { icon: "gift", text: "Elegant Gift Box Packaging" }
            ],
            pCareInstructions: [
                "Avoid submerging in water beyond splash resistance.",
                "Wipe the strap and case with a soft, dry cloth."
            ],
            pMainImage: "ProductImages/Product12/product12_01.jpeg",
            pImage1: "ProductImages/Product12/product12_02.jpeg",
            pImage2: "ProductImages/Product12/product12_03.jpeg",
            pImage3: "ProductImages/Product12/product12_04.jpeg",
            pImage4: "ProductImages/Product12/product12_05.jpeg",
            pDesc: "Timeless precision wrapped in modern elegance."
        },
        {
            pId: "P1213",
            pCategory: "Jewellery",
            pTag: "FINE COLLECTION",
            pName: "Luna Tennis Bracelet",
            pPrice: "3,999",
            pDiscount: 25,
            pRating: "5",
            pRiview: 276,
            pBadge: "Best Seller",
            pColorName: "Silver & Cubic Zirconia",
            pColorHex: "#d9d9d9",
            pFabric: "Rhodium-Plated Brass",
            pOccasion: "Wedding, Evening",
            pKeywords: ["bracelet", "tennis bracelet", "jewellery", "silver", "cubic zirconia", "fine collection"],
            pDim1Label: "Length",
            pDim1Value: "7 IN",
            pDim2Label: "Closure",
            pDim2Value: "Box Clasp",
            pHighlights: [
                { icon: "gem", text: "Brilliant-Cut Cubic Zirconia Stones" },
                { icon: "shield", text: "Rhodium Plating for Lasting Shine" },
                { icon: "hand", text: "Handset Stone Detailing" },
                { icon: "award", text: "Secure Box Clasp with Safety Lock" },
                { icon: "gift", text: "Presented in a Luxury Gift Box" }
            ],
            pCareInstructions: [
                "Keep away from water, perfumes and harsh chemicals.",
                "Store flat in the box provided to prevent tangling."
            ],
            pMainImage: "ProductImages/Product13/product13_01.jpeg",
            pImage1: "ProductImages/Product13/product13_02.jpeg",
            pImage2: "ProductImages/Product13/product13_03.jpeg",
            pImage3: "ProductImages/Product13/product13_04.jpeg",
            pImage4: "ProductImages/Product13/product13_05.jpeg",
            pDesc: "Brilliant diamonds crafted for timeless elegance."
        },
        {
            pId: "P1214",
            pCategory: "Footwear",
            pTag: "WALK COLLECTION",
            pName: "Luxury White Leather Sneakers",
            pPrice: "6,499",
            pDiscount: 15,
            pRating: "5",
            pRiview: 194,
            pBadge: null,
            pColorName: "Pearl White",
            pColorHex: "#f2f2f2",
            pFabric: "Italian Leather",
            pOccasion: "Casual, Everyday",
            pKeywords: ["sneakers", "white sneakers", "leather sneakers", "footwear", "casual shoes"],
            pDim1Label: "Sole",
            pDim1Value: "EVA Cushioned",
            pDim2Label: "Closure",
            pDim2Value: "Lace-Up",
            pHighlights: [
                { icon: "spool", text: "Premium Italian Leather Upper" },
                { icon: "shield", text: "Durable Rubber Outsole" },
                { icon: "hand", text: "Cushioned EVA Insole" },
                { icon: "award", text: "Handcrafted Stitch Detailing" },
                { icon: "leaf", text: "Breathable Interior Lining" }
            ],
            pCareInstructions: [
                "Wipe with a damp cloth; avoid machine washing.",
                "Use a protective spray to guard against stains."
            ],
            pMainImage: "ProductImages/Product14/product14_01.jpeg",
            pImage1: "ProductImages/Product14/product14_02.jpeg",
            pImage2: "ProductImages/Product14/product14_03.jpeg",
            pImage3: "ProductImages/Product14/product14_04.jpeg",
            pImage4: "ProductImages/Product14/product14_05.jpeg",
            pDesc: "Italian leather comfort with effortless luxury."
        },
        {
            pId: "P1215",
            pCategory: "Accessories",
            pTag: "ATELIER COLLECTION",
            pName: "Premium Cashmere Scarf",
            pPrice: "2,999",
            pDiscount: 20,
            pRating: "5",
            pRiview: 148,
            pBadge: null,
            pColorName: "Camel Beige",
            pColorHex: "#c19a6b",
            pFabric: "Pure Cashmere",
            pOccasion: "Winter, Everyday Layering",
            pKeywords: ["scarf", "cashmere scarf", "winter wear", "accessories", "camel", "atelier"],
            pDim1Label: "Length",
            pDim1Value: "72 IN",
            pDim2Label: "Width",
            pDim2Value: "28 IN",
            pHighlights: [
                { icon: "spool", text: "100% Pure Cashmere" },
                { icon: "leaf", text: "Ultra-Soft, Lightweight Feel" },
                { icon: "hand", text: "Fringed Hand-Finished Edges" },
                { icon: "shield", text: "Naturally Insulating Warmth" },
                { icon: "gift", text: "Gift-Ready Packaging" }
            ],
            pCareInstructions: [
                "Dry clean only to preserve the cashmere fibers.",
                "Store folded in a breathable cloth bag."
            ],
            pMainImage: "ProductImages/Product15/product15_01.jpeg",
            pImage1: "ProductImages/Product15/product15_02.jpeg",
            pImage2: "ProductImages/Product15/product15_03.jpeg",
            pImage3: "ProductImages/Product15/product15_04.jpeg",
            pImage4: "ProductImages/Product15/product15_05.jpeg",
            pDesc: "Ultra-soft cashmere crafted for everyday sophistication."
        },
        {
            pId: "P1216",
            pCategory: "Bags",
            pTag: "SIGNATURE LEATHER",
            pName: "Luxury Leather Tote Bag",
            pPrice: "8,999",
            pDiscount: 18,
            pRating: "5",
            pRiview: 231,
            pBadge: null,
            pColorName: "Caramel Tan",
            pColorHex: "#b3743a",
            pFabric: "Genuine Italian Leather",
            pOccasion: "Office, Travel",
            pKeywords: ["tote bag", "leather tote", "office bag", "caramel", "signature leather"],
            pDim1Label: "Height",
            pDim1Value: "12 IN",
            pDim2Label: "Width",
            pDim2Value: "15 IN",
            pHighlights: [
                { icon: "spool", text: "Genuine Italian Leather" },
                { icon: "shield", text: "Reinforced Stitched Handles" },
                { icon: "hanger", text: "Spacious Interior with Pockets" },
                { icon: "gem", text: "Gold-Tone Hardware Accents" },
                { icon: "hand", text: "Hand-Finished Edge Painting" }
            ],
            pCareInstructions: [
                "Wipe clean with a soft, dry cloth.",
                "Avoid overloading to maintain the bag's structure."
            ],
            pMainImage: "ProductImages/Product16/product16_01.jpeg",
            pImage1: "ProductImages/Product16/product16_02.jpeg",
            pImage2: "ProductImages/Product16/product16_03.jpeg",
            pImage3: "ProductImages/Product16/product16_04.jpeg",
            pImage4: "ProductImages/Product16/product16_05.jpeg",
            pDesc: "Elegant functionality crafted from premium Italian leather."
        },
        {
            pId: "P1217",
            pCategory: "Clothing",
            pTag: "MODERN ESSENTIALS",
            pName: "Wide-Leg Tailored Trousers",
            pPrice: "4,499",
            pDiscount: 12,
            pRating: "5",
            pRiview: 167,
            pBadge: null,
            pColorName: "Stone Beige",
            pColorHex: "#d6c7ad",
            pFabric: "Cotton-Blend Twill",
            pOccasion: "Office, Smart Casual",
            pKeywords: ["trousers", "wide-leg trousers", "tailored pants", "beige", "modern essentials"],
            pDim1Label: "Inseam",
            pDim1Value: "32 IN",
            pDim2Label: "Fit",
            pDim2Value: "Wide-Leg",
            pHighlights: [
                { icon: "spool", text: "Premium Cotton-Blend Twill" },
                { icon: "hanger", text: "High-Waisted Wide-Leg Fit" },
                { icon: "hand", text: "Tailored Front Crease" },
                { icon: "shield", text: "Wrinkle-Resistant Fabric" },
                { icon: "gem", text: "Concealed Side Zip Closure" }
            ],
            pCareInstructions: [
                "Machine wash cold; hang dry to retain shape.",
                "Iron on medium heat for a crisp finish."
            ],
            pMainImage: "ProductImages/Product17/product17_01.jpeg",
            pImage1: "ProductImages/Product17/product17_02.jpeg",
            pImage2: "ProductImages/Product17/product17_03.jpeg",
            pImage3: "ProductImages/Product17/product17_04.jpeg",
            pImage4: "ProductImages/Product17/product17_05.jpeg",
            pDesc: "Modern tailoring with refined comfort and elegance."
        },
        {
            pId: "P1218",
            pCategory: "Dresses",
            pTag: "EVENING COLLECTION",
            pName: "Luxury Silk Wrap Dress",
            pPrice: "7,999",
            pDiscount: 22,
            pRating: "5",
            pRiview: 203,
            pBadge: null,
            pColorName: "Emerald Green",
            pColorHex: "#0e6b4a",
            pFabric: "Pure Silk",
            pOccasion: "Evening, Party Wear",
            pKeywords: ["silk dress", "wrap dress", "emerald green", "evening wear", "party dress"],
            pDim1Label: "Dress Length",
            pDim1Value: "55 IN",
            pDim2Label: "Fit",
            pDim2Value: "Wrap Silhouette",
            pHighlights: [
                { icon: "spool", text: "100% Pure Silk Fabric" },
                { icon: "wave", text: "Elegant Wrap Silhouette" },
                { icon: "gem", text: "Fluid Draping with Sheen" },
                { icon: "hanger", text: "Adjustable Waist Tie" },
                { icon: "hand", text: "Fully Lined for Comfort" }
            ],
            pCareInstructions: [
                "Dry clean only to preserve the silk finish.",
                "Store on a padded hanger away from sunlight."
            ],
            pMainImage: "ProductImages/Product18/product18_01.jpeg",
            pImage1: "ProductImages/Product18/product18_02.jpeg",
            pImage2: "ProductImages/Product18/product18_03.jpeg",
            pImage3: "ProductImages/Product18/product18_04.jpeg",
            pImage4: "ProductImages/Product18/product18_05.jpeg",
            pDesc: "Flowing silk elegance designed for unforgettable evenings."
        },
        {
            pId: "P1219",
            pCategory: "Bags",
            pTag: "SIGNATURE LEATHER",
            pName: "Luxury Leather Crossbody Bag",
            pPrice: "7,499",
            pDiscount: 20,
            pRating: "5",
            pRiview: 188,
            pBadge: null,
            pColorName: "Chestnut Brown",
            pColorHex: "#7a4a2a",
            pFabric: "Genuine Leather",
            pOccasion: "Everyday, Travel",
            pKeywords: ["crossbody bag", "leather bag", "sling bag", "chestnut", "everyday bag"],
            pDim1Label: "Height",
            pDim1Value: "8 IN",
            pDim2Label: "Strap Drop",
            pDim2Value: "Adjustable",
            pHighlights: [
                { icon: "spool", text: "Genuine Leather Construction" },
                { icon: "hanger", text: "Adjustable Crossbody Strap" },
                { icon: "gem", text: "Gold-Tone Chain Detailing" },
                { icon: "shield", text: "Secure Zip Closure" },
                { icon: "hand", text: "Compact Everyday Silhouette" }
            ],
            pCareInstructions: [
                "Wipe clean with a soft, dry cloth.",
                "Store with the dust bag when not in use."
            ],
            pMainImage: "ProductImages/Product19/product19_01.jpeg",
            pImage1: "ProductImages/Product19/product19_02.jpeg",
            pImage2: "ProductImages/Product19/product19_03.jpeg",
            pImage3: "ProductImages/Product19/product19_04.jpeg",
            pImage4: "ProductImages/Product19/product19_05.jpeg",
            pDesc: "Compact luxury crafted for effortless everyday style."
        },
        {
            pId: "P1220",
            pCategory: "Home",
            pTag: "HOME COLLECTION",
            pName: "Midnight Oud Soy Candle",
            pPrice: "2,499",
            pDiscount: 15,
            pRating: "5",
            pRiview: 118,
            pBadge: "New Arrival",
            pColorName: "Amber Wax",
            pColorHex: "#b5741f",
            pFabric: "100% Soy Wax",
            pOccasion: "Home Decor, Gifting",
            pKeywords: ["candle", "soy candle", "oud", "home decor", "fragrance candle", "gift"],
            pDim1Label: "Burn Time",
            pDim1Value: "40+ Hours",
            pDim2Label: "Net Weight",
            pDim2Value: "220 G",
            pHighlights: [
                { icon: "leaf", text: "100% Natural Soy Wax" },
                { icon: "gem", text: "Warm Oud & Vanilla Fragrance" },
                { icon: "award", text: "Hand-Poured in Small Batches" },
                { icon: "shield", text: "Cotton Wick, Clean Burning" },
                { icon: "gift", text: "Elegant Gift-Ready Jar" }
            ],
            pCareInstructions: [
                "Trim the wick to 1/4 inch before each burn.",
                "Keep away from drafts and burn on a heat-safe surface."
            ],
            pMainImage: "ProductImages/Product20/product20_01.jpeg",
            pImage1: "ProductImages/Product20/product20_02.jpeg",
            pImage2: "ProductImages/Product20/product20_03.jpeg",
            pImage3: "ProductImages/Product20/product20_04.jpeg",
            pImage4: "ProductImages/Product20/product20_05.jpeg",
            pDesc: "Warm oud and vanilla fragrance for luxurious living."
        },
        {
            pId: "P1221",
            pCategory: "Ethnic Wear",
            pTag: "COUTURE COLLECTION",
            pName: "Royal Ivory Bridal Lehenga",
            pPrice: "24,999",
            pDiscount: 10,
            pRating: "5",
            pRiview: 142,
            pBadge: null,
            pColorName: "Ivory & Gold",
            pColorHex: "#efe6d0",
            pFabric: "Silk Blend with Zari Embroidery",
            pOccasion: "Wedding, Bridal",
            pKeywords: ["lehenga", "bridal lehenga", "ivory lehenga", "wedding wear", "couture", "ethnic wear"],
            pDim1Label: "Lehenga Length",
            pDim1Value: "42 IN",
            pDim2Label: "Includes",
            pDim2Value: "Blouse + Dupatta",
            pHighlights: [
                { icon: "gem", text: "Hand-Embroidered Zari Work" },
                { icon: "spool", text: "Premium Silk-Blend Fabric" },
                { icon: "hand", text: "Crafted by Skilled Artisans" },
                { icon: "hanger", text: "Includes Blouse & Dupatta" },
                { icon: "award", text: "Statement Bridal Silhouette" }
            ],
            pCareInstructions: [
                "Dry clean only; store flat wrapped in muslin cloth.",
                "Avoid contact with perfume and water to protect embroidery."
            ],
            pMainImage: "ProductImages/Product21/product21_01.jpeg",
            pImage1: "ProductImages/Product21/product21_02.jpeg",
            pImage2: "ProductImages/Product21/product21_03.jpeg",
            pImage3: "ProductImages/Product21/product21_04.jpeg",
            pImage4: "ProductImages/Product21/product21_05.jpeg",
            pDesc: "Handcrafted couture designed for timeless celebrations."
        },
        {
            pId: "P1222",
            pCategory: "Watches",
            pTag: "TIME COLLECTION",
            pName: "Celeste Étoile Moonphase Watch",
            pPrice: "8,999",
            pDiscount: 12,
            pRating: "5",
            pRiview: 223,
            pBadge: null,
            pColorName: "Midnight Blue",
            pColorHex: "#1c2b4a",
            pFabric: "Stainless Steel Case",
            pOccasion: "Formal, Gifting",
            pKeywords: ["watch", "moonphase watch", "midnight blue", "time collection", "luxury watch"],
            pDim1Label: "Dial Size",
            pDim1Value: "34 MM",
            pDim2Label: "Feature",
            pDim2Value: "Moonphase Display",
            pHighlights: [
                { icon: "award", text: "Swiss-Inspired Moonphase Movement" },
                { icon: "shield", text: "Sapphire-Coated Crystal Glass" },
                { icon: "gem", text: "Midnight Blue Starburst Dial" },
                { icon: "lock", text: "5 ATM Water Resistance" },
                { icon: "gift", text: "Presented in a Signature Box" }
            ],
            pCareInstructions: [
                "Avoid magnetic fields near the watch movement.",
                "Service the movement periodically for lasting accuracy."
            ],
            pMainImage: "ProductImages/Product22/product22_01.jpeg",
            pImage1: "ProductImages/Product22/product22_02.jpeg",
            pImage2: "ProductImages/Product22/product22_03.jpeg",
            pImage3: "ProductImages/Product22/product22_04.jpeg",
            pImage4: "ProductImages/Product22/product22_05.jpeg",
            pDesc: "Swiss-inspired precision wrapped in timeless elegance."
        },
        {
            pId: "P1223",
            pCategory: "Dresses",
            pTag: "EVENING COUTURE",
            pName: "Emerald Velvet Evening Gown",
            pPrice: "14,999",
            pDiscount: 15,
            pRating: "5",
            pRiview: 186,
            pBadge: null,
            pColorName: "Emerald Green",
            pColorHex: "#0b5c3a",
            pFabric: "Premium Velvet",
            pOccasion: "Evening, Red Carpet",
            pKeywords: ["gown", "velvet gown", "evening gown", "emerald", "red carpet dress"],
            pDim1Label: "Gown Length",
            pDim1Value: "60 IN",
            pDim2Label: "Fit",
            pDim2Value: "Fitted Silhouette",
            pHighlights: [
                { icon: "spool", text: "Luxurious Velvet Fabric" },
                { icon: "wave", text: "Fitted Floor-Length Silhouette" },
                { icon: "gem", text: "Rich Color Depth with Subtle Sheen" },
                { icon: "hanger", text: "Concealed Back Zip Closure" },
                { icon: "hand", text: "Fully Lined for Structure" }
            ],
            pCareInstructions: [
                "Dry clean only to preserve the velvet pile.",
                "Steam to remove creases; avoid direct ironing."
            ],
            pMainImage: "ProductImages/Product23/product23_01.jpeg",
            pImage1: "ProductImages/Product23/product23_02.jpeg",
            pImage2: "ProductImages/Product23/product23_03.jpeg",
            pImage3: "ProductImages/Product23/product23_04.jpeg",
            pImage4: "ProductImages/Product23/product23_05.jpeg",
            pDesc: "Luxury velvet couture crafted for unforgettable evenings."
        },
        {
            pId: "P1224",
            pCategory: "Clothing",
            pTag: "MODERN ELEGANCE",
            pName: "Ivory Tailored Jumpsuit",
            pPrice: "8,499",
            pDiscount: 12,
            pRating: "5",
            pRiview: 154,
            pBadge: null,
            pColorName: "Ivory White",
            pColorHex: "#f0ead9",
            pFabric: "Crepe Fabric",
            pOccasion: "Office, Evening",
            pKeywords: ["jumpsuit", "ivory jumpsuit", "tailored jumpsuit", "modern elegance", "clothing"],
            pDim1Label: "Length",
            pDim1Value: "58 IN",
            pDim2Label: "Fit",
            pDim2Value: "Tailored",
            pHighlights: [
                { icon: "spool", text: "Premium Crepe Fabric" },
                { icon: "hanger", text: "Tailored Wide-Leg Fit" },
                { icon: "hand", text: "Belted Waist Detailing" },
                { icon: "shield", text: "Wrinkle-Resistant Finish" },
                { icon: "gem", text: "Concealed Back Zip" }
            ],
            pCareInstructions: [
                "Dry clean recommended for best results.",
                "Steam gently to remove creases before wear."
            ],
            pMainImage: "ProductImages/Product24/product24_01.jpeg",
            pImage1: "ProductImages/Product24/product24_02.jpeg",
            pImage2: "ProductImages/Product24/product24_03.jpeg",
            pImage3: "ProductImages/Product24/product24_04.jpeg",
            pImage4: "ProductImages/Product24/product24_05.jpeg",
            pDesc: "Minimal tailoring with timeless contemporary sophistication."
        },
        {
            pId: "P1225",
            pCategory: "Dresses",
            pTag: "MIDNIGHT COLLECTION",
            pName: "Noir Sequin Cocktail Dress",
            pPrice: "10,999",
            pDiscount: 20,
            pRating: "5",
            pRiview: 221,
            pBadge: null,
            pColorName: "Jet Black",
            pColorHex: "#111111",
            pFabric: "Sequin Mesh",
            pOccasion: "Party, Night Events",
            pKeywords: ["cocktail dress", "sequin dress", "black dress", "party wear", "midnight collection"],
            pDim1Label: "Dress Length",
            pDim1Value: "36 IN",
            pDim2Label: "Fit",
            pDim2Value: "Bodycon",
            pHighlights: [
                { icon: "gem", text: "All-Over Hand-Applied Sequins" },
                { icon: "wave", text: "Figure-Hugging Silhouette" },
                { icon: "hanger", text: "Fully Lined Interior" },
                { icon: "shield", text: "Concealed Side Zip Closure" },
                { icon: "hand", text: "Reinforced Stitching for Durability" }
            ],
            pCareInstructions: [
                "Dry clean only; do not iron directly on sequins.",
                "Store flat or on a padded hanger to prevent snagging."
            ],
            pMainImage: "ProductImages/Product25/product25_01.jpeg",
            pImage1: "ProductImages/Product25/product25_02.jpeg",
            pImage2: "ProductImages/Product25/product25_03.jpeg",
            pImage3: "ProductImages/Product25/product25_04.jpeg",
            pImage4: "ProductImages/Product25/product25_05.jpeg",
            pDesc: "Sparkling glamour designed for luxury night events."
        },
        {
            pId: "P1226",
            pCategory: "Ethnic Wear",
            pTag: "HERITAGE COLLECTION",
            pName: "Royal Ivory Sharara Set",
            pPrice: "12,499",
            pDiscount: 18,
            pRating: "5",
            pRiview: 203,
            pBadge: null,
            pColorName: "Ivory & Gold",
            pColorHex: "#efe6d0",
            pFabric: "Georgette with Zari Embroidery",
            pOccasion: "Wedding, Festive",
            pKeywords: ["sharara set", "ivory sharara", "ethnic wear", "heritage collection", "wedding wear"],
            pDim1Label: "Kurta Length",
            pDim1Value: "44 IN",
            pDim2Label: "Includes",
            pDim2Value: "Kurta + Sharara + Dupatta",
            pHighlights: [
                { icon: "gem", text: "Intricate Zari Embroidery" },
                { icon: "spool", text: "Premium Georgette Fabric" },
                { icon: "hand", text: "Hand-Finished Embellishments" },
                { icon: "hanger", text: "Includes Kurta, Sharara & Dupatta" },
                { icon: "award", text: "Inspired by Royal Heritage Motifs" }
            ],
            pCareInstructions: [
                "Dry clean only to preserve embroidery detailing.",
                "Store folded in a cotton cloth away from sunlight."
            ],
            pMainImage: "ProductImages/Product26/product26_01.jpeg",
            pImage1: "ProductImages/Product26/product26_02.jpeg",
            pImage2: "ProductImages/Product26/product26_03.jpeg",
            pImage3: "ProductImages/Product26/product26_04.jpeg",
            pImage4: "ProductImages/Product26/product26_05.jpeg",
            pDesc: "Intricate embroidery inspired by timeless royal elegance."
        },
        {
            pId: "P1227",
            pCategory: "Ethnic Wear",
            pTag: "FESTIVE EDIT",
            pName: "Pearl Beige Straight Suit",
            pPrice: "7,999",
            pDiscount: 10,
            pRating: "5",
            pRiview: 137,
            pBadge: null,
            pColorName: "Pearl Beige",
            pColorHex: "#e6d7b8",
            pFabric: "Chanderi Silk",
            pOccasion: "Festive, Daywear",
            pKeywords: ["straight suit", "beige suit", "chanderi silk", "festive edit", "ethnic wear"],
            pDim1Label: "Kurta Length",
            pDim1Value: "46 IN",
            pDim2Label: "Includes",
            pDim2Value: "Kurta + Pant + Dupatta",
            pHighlights: [
                { icon: "spool", text: "Pure Chanderi Silk Fabric" },
                { icon: "gem", text: "Hand-Embroidered Neckline" },
                { icon: "hanger", text: "Includes Kurta, Pant & Dupatta" },
                { icon: "hand", text: "Finished by Skilled Artisans" },
                { icon: "leaf", text: "Lightweight, Breathable Drape" }
            ],
            pCareInstructions: [
                "Dry clean only for best fabric care.",
                "Store flat wrapped in muslin cloth."
            ],
            pMainImage: "ProductImages/Product27/product27_01.jpeg",
            pImage1: "ProductImages/Product27/product27_02.jpeg",
            pImage2: "ProductImages/Product27/product27_03.jpeg",
            pImage3: "ProductImages/Product27/product27_04.jpeg",
            pImage4: "ProductImages/Product27/product27_05.jpeg",
            pDesc: "Graceful festive silhouette with handcrafted embroidery."
        },
        {
            pId: "P1228",
            pCategory: "Sarees",
            pTag: "SIGNATURE SAREE",
            pName: "Blush Organza Designer Saree",
            pPrice: "13,999",
            pDiscount: 16,
            pRating: "5",
            pRiview: 248,
            pBadge: null,
            pColorName: "Blush Pink",
            pColorHex: "#e3a7ad",
            pFabric: "Pure Organza Silk",
            pOccasion: "Festive, Party Wear",
            pKeywords: ["saree", "organza saree", "blush pink saree", "designer saree", "signature saree"],
            pDim1Label: "Saree Length",
            pDim1Value: "5.5 MTR",
            pDim2Label: "Blouse Piece",
            pDim2Value: "0.8 MTR",
            pHighlights: [
                { icon: "spool", text: "Pure Organza Silk Fabric" },
                { icon: "gem", text: "Hand-Embroidered Motifs" },
                { icon: "wave", text: "Lightweight Flowing Drape" },
                { icon: "hanger", text: "Includes Unstitched Blouse Piece" },
                { icon: "hand", text: "Crafted by Skilled Artisans" }
            ],
            pCareInstructions: [
                "Dry clean only to preserve the organza texture.",
                "Store flat wrapped in muslin cloth away from sunlight."
            ],
            pMainImage: "ProductImages/Product28/product28_01.jpeg",
            pImage1: "ProductImages/Product28/product28_02.jpeg",
            pImage2: "ProductImages/Product28/product28_03.jpeg",
            pImage3: "ProductImages/Product28/product28_04.jpeg",
            pImage4: "ProductImages/Product28/product28_05.jpeg",
            pDesc: "Hand-embroidered elegance with luxurious organza drape."
        },
        {
            pId: "P1229",
            pCategory: "Ethnic Wear",
            pTag: "ROYAL OCCASION",
            pName: "Emerald Anarkali Set",
            pPrice: "15,499",
            pDiscount: 22,
            pRating: "5",
            pRiview: 287,
            pBadge: "Best Seller",
            pColorName: "Emerald Green & Gold",
            pColorHex: "#0e6b4a",
            pFabric: "Silk Blend with Zari Work",
            pOccasion: "Wedding, Festive",
            pKeywords: ["anarkali", "emerald anarkali", "ethnic wear", "royal occasion", "wedding wear"],
            pDim1Label: "Anarkali Length",
            pDim1Value: "52 IN",
            pDim2Label: "Includes",
            pDim2Value: "Kurta + Churidar + Dupatta",
            pHighlights: [
                { icon: "gem", text: "Elaborate Zari & Thread Work" },
                { icon: "spool", text: "Rich Silk-Blend Fabric" },
                { icon: "wave", text: "Flowing Anarkali Silhouette" },
                { icon: "hanger", text: "Includes Churidar & Dupatta" },
                { icon: "hand", text: "Hand-Finished Embellishments" }
            ],
            pCareInstructions: [
                "Dry clean only to protect embroidery and zari work.",
                "Store folded in cotton cloth away from direct light."
            ],
            pMainImage: "ProductImages/Product29/product29_01.jpeg",
            pImage1: "ProductImages/Product29/product29_02.jpeg",
            pImage2: "ProductImages/Product29/product29_03.jpeg",
            pImage3: "ProductImages/Product29/product29_04.jpeg",
            pImage4: "ProductImages/Product29/product29_05.jpeg",
            pDesc: "Flowing royal elegance with premium handcrafted detailing."
        },
        {
            pId: "P1230",
            pCategory: "Ethnic Wear",
            pTag: "FESTIVE COLLECTION",
            pName: "Rose Pink Designer Suit",
            pPrice: "9,999",
            pDiscount: 14,
            pRating: "5",
            pRiview: 165,
            pBadge: null,
            pColorName: "Rose Pink",
            pColorHex: "#d67a95",
            pFabric: "Georgette",
            pOccasion: "Festive, Daywear",
            pKeywords: ["designer suit", "rose pink suit", "georgette suit", "festive collection", "ethnic wear"],
            pDim1Label: "Kurta Length",
            pDim1Value: "44 IN",
            pDim2Label: "Includes",
            pDim2Value: "Kurta + Pant + Dupatta",
            pHighlights: [
                { icon: "spool", text: "Premium Georgette Fabric" },
                { icon: "gem", text: "Delicate Hand Embroidery" },
                { icon: "hanger", text: "Includes Kurta, Pant & Dupatta" },
                { icon: "hand", text: "Finished by Skilled Artisans" },
                { icon: "leaf", text: "Lightweight, Comfortable Drape" }
            ],
            pCareInstructions: [
                "Dry clean only for best results.",
                "Store flat wrapped in a cotton cloth."
            ],
            pMainImage: "ProductImages/Product30/product30_01.jpeg",
            pImage1: "ProductImages/Product30/product30_02.jpeg",
            pImage2: "ProductImages/Product30/product30_03.jpeg",
            pImage3: "ProductImages/Product30/product30_04.jpeg",
            pImage4: "ProductImages/Product30/product30_05.jpeg",
            pDesc: "Elegant festive attire finished with delicate embroidery."
        },
        {
            pId: "P1231",
            pCategory: "Ethnic Wear",
            pTag: "LUMORA COUTURE",
            pName: "Ruby Sharara Luxury Set",
            pPrice: "11,999",
            pDiscount: 25,
            pRating: "5",
            pRiview: 312,
            pBadge: "Best Seller",
            pColorName: "Ruby Red & Gold",
            pColorHex: "#8f0d1f",
            pFabric: "Silk Blend with Zari Embroidery",
            pOccasion: "Wedding, Festive",
            pKeywords: ["sharara", "ruby sharara", "lumora couture", "ethnic wear", "wedding set"],
            pDim1Label: "Kurta Length",
            pDim1Value: "46 IN",
            pDim2Label: "Includes",
            pDim2Value: "Kurta + Sharara + Dupatta",
            pHighlights: [
                { icon: "gem", text: "Statement Zari & Sequin Work" },
                { icon: "spool", text: "Luxurious Silk-Blend Fabric" },
                { icon: "hand", text: "Hand-Finished Embellishments" },
                { icon: "hanger", text: "Includes Kurta, Sharara & Dupatta" },
                { icon: "award", text: "Crafted for Grand Celebrations" }
            ],
            pCareInstructions: [
                "Dry clean only to preserve embroidery detailing.",
                "Store flat wrapped in muslin cloth away from sunlight."
            ],
            pMainImage: "ProductImages/Product31/product31_01.jpeg",
            pImage1: "ProductImages/Product31/product31_02.jpeg",
            pImage2: "ProductImages/Product31/product31_03.jpeg",
            pImage3: "ProductImages/Product31/product31_04.jpeg",
            pImage4: "ProductImages/Product31/product31_05.jpeg",
            pDesc: "Statement festive couture with luxurious handcrafted finish."
        },
        {
            pId: "P1232",
            pCategory: "Sarees",
            pTag: "HERITAGE COUTURE",
            pName: "Heritage Banarasi Silk Saree",
            pPrice: "16,999",
            pDiscount: 18,
            pRating: "5",
            pRiview: 247,
            pBadge: "Best Seller",
            pColorName: "Royal Wine Red",
            pColorHex: "#6e1330",
            pFabric: "Pure Banarasi Silk",
            pOccasion: "Wedding, Festive, Party",
            pKeywords: ["banarasi saree", "silk saree", "heritage couture", "wine red saree", "wedding saree"],
            pDim1Label: "Saree Length",
            pDim1Value: "5.5 MTR",
            pDim2Label: "Blouse Piece",
            pDim2Value: "0.8 MTR",
            pHighlights: [
                { icon: "spool", text: "Pure Handwoven Banarasi Silk" },
                { icon: "gem", text: "Antique Gold Zari Weaving" },
                { icon: "wave", text: "Grand Woven Pallu" },
                { icon: "hanger", text: "Includes Unstitched Blouse Piece" },
                { icon: "hand", text: "Crafted by Skilled Artisans" }
            ],
            pCareInstructions: [
                "Dry clean only to preserve the silk's sheen and zari work.",
                "Store folded in a muslin cloth away from direct sunlight."
            ],
            pMainImage: "ProductImages/Product32/product32_01.jpeg",
            pImage1: "ProductImages/Product32/product32_02.jpeg",
            pImage2: "ProductImages/Product32/product32_03.jpeg",
            pImage3: "ProductImages/Product32/product32_04.jpeg",
            pImage4: "ProductImages/Product32/product32_05.jpeg",
            pDesc: "Handwoven Banarasi silk adorned with timeless antique gold zari craftsmanship."
        }
    ]
    
}